# Supabase PostgreSQL Configuration Profile
spring.datasource.url=jdbc:postgresql://db.fyzlfmzwgrskulwalzvr.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Vasanth@1234!@#$
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

goalforge.jwt.secret=b4rq5GBiA3rnxrACNMFtQpeY3T/7x2pFt6vZA5td2UoY/Qrn4lk8A+ichla4B04LZqs/1+mymMAmJBNgdx4jrA==
goalforge.jwt.expiration-ms=86400000

supabase.url=https://fyzlfmzwgrskulwalzvr.supabase.co
supabase.anon-key=sb_publishable_FQMpiLWcCuQjUGl01I-5bg_EOi5Ta4P
supabase.service-role-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5emxmbXp3Z3Jza3Vsd2FsenZyIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4OTUyNDM1MywiZXhwIjoyMTA1MTAwMzUzfQ.-arlQaB0zPrCKjOO5xEQoSMpSjql9E-1tIhwEvO17-o
